### ISSUE TITLE
Faults can bring the connector down

### ISSUE THREAD

**Issue by rollulus** [Eneco/kafka-connect-nationalgrid#1]
```[2017-01-07 07:12:03,482] ERROR Task national_grid_source-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
Fault(Fault(Faultcode({http://www.w3.org/2003/05/soap-envelope}Receiver,None),Faultreason(List(Reasontext(Unknown processing error,en))),None,None,Some(Detail(List(),Map()))), Some(Detail(List(),Map())), )
	at scalaxb.SoapClientsAsync$SoapClientAsync$$anonfun$buildResponse$1.apply(soap12_async.scala:85)
	at scalaxb.SoapClientsAsync$SoapClientAsync$$anonfun$buildResponse$1.apply(soap12_async.scala:74)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[2017-01-07 07:12:03,490] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)```

**Comment by rollulus** [comment]
see aac1e9ac7c5e3f300e4572f3659b27d629cca353; closing for now.
